CREATE TABLE USERS
(
	USER_ID INT NOT NULL AUTO_INCREMENT,
	USER_NAME VARCHAR(50) NOT NULL UNIQUE,
	PASSWORD BLOB NOT NULL,
	IS_ADMIN TINYINT NOT NULL DEFAULT 0,
	IS_NEED_CHANGE_PASSWORD TINYINT NOT NULL DEFAULT 0,
	PRIMARY KEY (USER_ID) 
);