CREATE TABLE LOG
(
	EVENT_ID INT NOT NULL AUTO_INCREMENT,
	EVENT_DATE TIMESTAMP NOT NULL DEFAULT NOW(),
	EVENT_LEVEL VARCHAR(20) NOT NULL DEFAULT 'INFO',
	EVENT_DESC VARCHAR(200) NOT NULL DEFAULT 'NO DESCIPTION',
	PRIMARY KEY(EVENT_ID)
);